name: transit
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.13=h2bbff1b_0
  - pip=23.3.1=py310haa95532_0
  - python=3.10.13=he1021f5_0
  - setuptools=68.2.2=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - beautifulsoup4==4.12.3
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - gtfs-realtime-bindings==1.0.0
    - idna==3.6
    - numpy==1.26.4
    - pandas==2.2.1
    - protobuf==4.25.3
    - protobuf3-to-dict==0.1.5
    - python-dateutil==2.8.2
    - pytz==2024.1
    - requests==2.31.0
    - six==1.16.0
    - soupsieve==2.5
    - tzdata==2024.1
    - urllib3==2.2.1
